services:
  otelcol:
    image: otel/opentelemetry-collector-contrib:0.109.0
    volumes:
      - ./otelcol-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
    environment:
      - GRAFANA_CLOUD_USERNAME
      - GRAFANA_CLOUD_API_KEY
      - GRAFANA_CLOUD_ENDPOINT
